import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="" data-new-gr-c-s-check-loaded="14.1252.0"data-gr-ext-installed="" cz-shortcut-listen="true">
        {children}
      </body>
    </html>
  );
}
